---
- name: playbook to provision most of the MoodleBox
  hosts: all
  vars:
    ansible_user: 'root'
  become: 'true'

  vars_files:
    - default.config.yml

  pre_tasks:
    - debug:
        msg: 'Beginning of build: {{ ansible_date_time.iso8601 }}'
      delegate_to: localhost
      become: false

    - name: include customised variables
      include_vars: '{{ item }}'
      with_fileglob:
        - config.yml

  post_tasks:
    - debug:
        msg: 'End of build: {{ ansible_date_time.iso8601 }}'
      delegate_to: localhost
      become: false

  roles:
    - rpi-settings
    - apt
    - { role: firmware, when: moodlebox_update_firmware | bool }
    - { role: hostname, when: moodlebox_set_hostname | bool }
    - useraccount
    - { role: timezone, when: moodlebox_set_timezone | bool }
    - { role: locales, when: moodlebox_set_locale | bool }
    - wifi
    - database
    - packages
    - package-config
    - partition-resize
    - access-point
    - zeroconf
    - webserver
    - ipforwarding
    - moodleuninstall
    - moodledatabase
    - moodleinstall
    - cron
    - adminer
    - cert
    - branding
    - cleanup
