---
- name: playbook to upgrade the MoodleBox to the last version
  hosts: all
  vars:
    ansible_user: '{{ moodlebox_username }}'
    ansible_password: '{{ moodlebox_password }}'
  become: 'true'

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: include customised variables
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml

    - name: get MoodleBox current version info
      slurp:
        src: "/etc/moodlebox-info"
      ignore_errors: 'yes'
      register: moodleboxinfo

    - name: alert if upgrade cannot proceed
      debug:
        msg: "This is not a MoodleBox and cannot be upgraded by this script. Aborting."
      when:
        moodleboxinfo.failed

    - name: aborts upgrade if not a MoodleBox
      meta:
        end_play
      when:
        moodleboxinfo.failed

  roles:
    - rpi-settings
    - apt
    - wifi
    - packages
    - package-config
    - moodleupgrade
    - cron
    - adminer
    - cert
    - branding
