---
- name: playbook to upgrade the MoodleBox to the last version
  hosts: all
  vars:
    ansible_user: '{{ moodlebox_username }}'
    ansible_password: '{{ moodlebox_password }}'
  become: 'true'

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: include customised variables
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml

  roles:
    - rpi-settings
    - apt
    - wifi
    - packages
    - package-config
    - moodleupgrade
    - cron
    - adminer
    - cert
    - branding
