---

- name: format release date using locales
  command: "date --date={{ moodlebox_release_date }} '+%-d %B %Y'"
  environment:
    - LC_ALL: '{{ item.1 }}'
  with_indexed_items: '{{ moodlebox_locales }}'
  register: 'formatted_dates'
  when: 'formatted_dates is not defined or item.0 < moodlebox_locales|length'

- name: set vars with formatted dates
  set_fact: '{{ item.0 | regex_replace("^(.*)_.*UTF-8$", "moodlebox_release_date_\1") }}={{ item.1.stdout }}'
  with_together:
    - '{{ moodlebox_locales }}'
    - '{{ formatted_dates.results }}'

- name: set summary string with formatted dates
  set_fact:
    moodlebox_moodle_summary: '{{ moodlebox_moodle_summary }}'

- name: clean previous installation
  import_tasks: clean.yml
  when: not upgrade_moodlebox | bool

- name: create database
  import_tasks: db.yml
  when: not upgrade_moodlebox | bool

- name: get Moodle and install it
  import_tasks: coreinstall.yml
  when: not upgrade_moodlebox | bool

- name: upgrade Moodle
  import_tasks: upgrade.yml
  when: upgrade_moodlebox | bool

- name: get MoodleBox plugin and install it
  import_tasks: moodleboxplugin.yml
  when: not upgrade_moodlebox | bool

- name: install MathJax library
  import_tasks: mathjax.yml

- name: compile themes scss
  import_tasks: themes.yml
  when: not upgrade_moodlebox | bool

- name: install adminer latest release
  get_url:
    url: 'https://www.adminer.org/latest.php'
    dest: '{{ moodlebox_moodle_source_dir }}/adminer.php'
    owner: 'www-data'
    group: '{{ moodlebox_username }}'
    mode: '0664'

- name: copy root CA certificate
  copy:
    src: 'home/files/moodleboxCA.crt'
    dest: '/home/{{ moodlebox_username }}/files/moodleboxCA.crt'
    owner: '{{ moodlebox_username }}'
    group: 'www-data'

- name: configure crons
  import_tasks: cron.yml
  when: not upgrade_moodlebox | bool

- meta: flush_handlers
