---
- name: get Moodle version '{{ moodlebox_moodle_branch }}' from git repository
  git:
    repo: 'git://git.moodle.org/moodle.git'
    version: '{{ moodlebox_moodle_branch }}'
    dest: '{{ moodlebox_moodle_source_dir }}'
    force: 'yes'
    depth: 1
  register: moodle_updated

- name: get MoodleBox plugin version '{{ moodlebox_moodlebox_plugin_version }}' from git repository
  git:
    repo: 'https://github.com/moodlebox/moodle-tool_moodlebox.git'
    version: '{{ moodlebox_moodlebox_plugin_version }}'
    dest: '{{ moodlebox_moodle_source_dir }}/admin/tool/moodlebox'
    force: 'yes'
    depth: 1
  register: moodlebox_plugin_updated

- name: set owner, group and permissions for moodle and moodledata directories
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'www-data'
    group: '{{ moodlebox_username }}'
    mode: 'ug+w,o-w'
    recurse: 'yes'
  with_items:
    - '{{ moodlebox_moodle_source_dir }}'
    - '{{ moodlebox_moodle_data_dir }}'

- name: create sudoers file for MoodleBox plugin usage
  copy:
    src: 'etc/sudoers.d/020_www-data-nopasswd'
    dest: '/etc/sudoers.d/020_www-data-nopasswd'
    mode: '0440'
    validate: 'visudo -cf %s'
