---
- name: download latest stable Moodle and MoodleBox plugin
  import_tasks: download.yml

- name: get latest stable Moodle version and upgrade
  import_tasks: upgrade.yml

- name: install MathJax library
  import_tasks: mathjax.yml

- name: compile themes scss
  import_tasks: themes.yml
