---

- name: get MathJax library version '{{ moodlebox_mathjax_version }}' from git repository
  git:
    repo: 'git://github.com/mathjax/MathJax.git'
    dest: '{{ moodlebox_moodle_source_dir }}/lib/MathJax'
    version: '{{ moodlebox_mathjax_version }}'
    force: 'yes'
    depth: 1
  notify: set MathJax library file permissions
