---

- name: upgrade Moodle to version '{{ moodlebox_moodle_branch }}' from git repository
  git:
    repo: 'git://git.moodle.org/moodle.git'
    version: '{{ moodlebox_moodle_branch }}'
    dest: '{{ moodlebox_moodle_source_dir }}'
    force: 'yes'
    depth: 1

- name: upgrade MoodleBox plugin to version '{{ moodlebox_moodlebox_plugin_version }}' from git repository
  git:
    repo: 'https://github.com/moodlebox/moodle-tool_moodlebox.git'
    version: '{{ moodlebox_moodlebox_plugin_version }}'
    dest: '{{ moodlebox_moodle_source_dir }}/admin/tool/moodlebox'
    force: 'yes'
    depth: 1

# https://github.com/HCPSS/ansible-role-moodle/blob/master/tasks/install.yml
- name: install Moodle via CLI
  command: '/usr/bin/php "{{ moodlebox_moodle_source_dir }}/admin/cli/install.php"
    --lang="{{ moodlebox_moodle_lang }}"
    --wwwroot="http://{{ moodlebox_hostname }}.{{ moodlebox_tld }}"
    --dataroot="{{ moodlebox_moodle_data_dir }}"
    --dbtype="mariadb"
    --dbname="{{ moodlebox_moodle_db }}"
    --prefix="{{ moodlebox_moodle_db_prefix }}"
    --dbuser="{{ moodlebox_db_username }}"
    --dbpass="{{ moodlebox_db_password }}"
    --fullname="{{ moodlebox_moodle_name }}"
    --shortname="{{ moodlebox_moodle_name }}"
    --summary="{{ moodlebox_moodle_summary }}"
    --adminuser="{{ moodlebox_moodle_username }}"
    --adminpass="{{ moodlebox_moodle_password }}"
    --adminemail="{{ moodlebox_moodle_username }}@{{ moodlebox_hostname }}.invalid"
    --non-interactive
    --allow-unstable
    --agree-license'
  args:
    chdir: '{{ moodlebox_moodle_source_dir }}'
    creates: '{{ moodlebox_moodle_source_dir }}/config.php'

- name: set Moodle config file owner, group and permissions
  file:
    path: '{{ moodlebox_moodle_source_dir }}/config.php'
    owner: 'www-data'
    group: '{{ moodlebox_username }}'
    mode: 'ug+w,o-w'

- name: put Moodle into the maintenance mode
  command: '/usr/bin/php "{{ moodlebox_moodle_source_dir }}/admin/cli/maintenance.php" --enable'
  args:
    creates: '{{ moodlebox_moodle_data_dir }}/climaintenance.html'

- name: upgrade Moodle via CLI
  command: '/usr/bin/php "{{ moodlebox_moodle_source_dir }}/admin/cli/upgrade.php"
    --non-interactive
    --allow-unstable'
  args:
    chdir: '{{ moodlebox_moodle_source_dir }}'
  register: moodle_upgrade
  changed_when: moodle_upgrade.rc == 0

- name: put Moodle off maintenance mode
  command: '/usr/bin/php "{{ moodlebox_moodle_source_dir }}/admin/cli/maintenance.php" --disable'
  args:
    removes: '{{ moodlebox_moodle_data_dir }}/climaintenance.html'
