---
- name: put Moodle into maintenance mode
  command: '/usr/bin/php "{{ moodlebox_moodle_source_dir }}/admin/cli/maintenance.php" --enable'
  args:
    creates: '{{ moodlebox_moodle_data_dir }}/climaintenance.html'

- name: upgrade Moodle via CLI
  command: '/usr/bin/php "{{ moodlebox_moodle_source_dir }}/admin/cli/upgrade.php"
    --non-interactive
    --allow-unstable'
  args:
    chdir: '{{ moodlebox_moodle_source_dir }}'
  register: moodle_upgrade
  changed_when: moodle_upgrade.rc == 0

- name: put Moodle off maintenance mode
  command: '/usr/bin/php "{{ moodlebox_moodle_source_dir }}/admin/cli/maintenance.php" --disable'
  args:
    removes: '{{ moodlebox_moodle_data_dir }}/climaintenance.html'
